vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set("n", "WW", "<cmd>w<CR>")
vim.keymap.set("n", "<leader>s", "<cmd>normal Go<CR>i")
vim.keymap.set("i", "<A-h>", "<Left>")
vim.keymap.set("i", "<A-j>", "<Down>")
vim.keymap.set("i", "<A-k>", "<Up>")
vim.keymap.set("i", "<A-l>", "<Right>")
vim.keymap.set("n", "<leader>h","<cmd>wincmd h<CR>")
vim.keymap.set("n", "<leader>j","<cmd>wincmd j<CR>")
vim.keymap.set("n", "<leader>k","<cmd>wincmd k<CR>")
vim.keymap.set("n", "<leader>l","<cmd>wincmd l<CR>")
